// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gerenciador_de_escolas.Repository;

namespace gerenciadordeescolas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("gerenciador_de_escolas.Models.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("endereco");

                    b.Property<string>("matricula");

                    b.Property<string>("nome");

                    b.Property<string>("telefone");

                    b.Property<int?>("turmaid");

                    b.HasKey("id");

                    b.HasIndex("turmaid");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("gerenciador_de_escolas.Models.Escola", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("endereco");

                    b.Property<string>("logomarca");

                    b.Property<string>("nome");

                    b.Property<string>("telefone");

                    b.HasKey("id");

                    b.ToTable("escolas");
                });

            modelBuilder.Entity("gerenciador_de_escolas.Models.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ano");

                    b.Property<int?>("escolaid");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.HasIndex("escolaid");

                    b.ToTable("turmas");
                });

            modelBuilder.Entity("gerenciador_de_escolas.Models.Aluno", b =>
                {
                    b.HasOne("gerenciador_de_escolas.Models.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaid");
                });

            modelBuilder.Entity("gerenciador_de_escolas.Models.Turma", b =>
                {
                    b.HasOne("gerenciador_de_escolas.Models.Escola", "escola")
                        .WithMany()
                        .HasForeignKey("escolaid");
                });
#pragma warning restore 612, 618
        }
    }
}
